### ISSUE TITLE
Map markers aren't working with Leaflet

### ISSUE THREAD

**Issue by skoeven** [tectonicus/tectonicus#102]
Map markers and map centering are currently broken.  The code that converted between a 3d Minecraft coordinate and a 2d Google Maps coordinate is not working with Leaflet.  Need to do more research to figure out how to do this correctly with Leaflet.

**Comment by rawbits2010** [comment]
With L.CRS.Simple and basic trigonometry. The question is, how to get the 2D x,y elevation from the orto camera angle for the 3D x,y,z world coordinates.
I'll probably ask someone smarter than me and add the exporter code to the Java project. My Leaflet display is currently using eyeballed magic numbers. (Fixed camera angle and elevation, pixel counting, refining on systematically placed coords in a 2000 by 2000 test map.)

**Comment by skoeven** [comment]
Map markers are working again in [v2.29](https://github.com/tectonicus/tectonicus/releases/tag/v2.29)
