### ISSUE TITLE
Version recommendation?

### ISSUE THREAD

**Issue by ckbrewer33** [tectonicus/tectonicus#103]
Can you recommend a version that tectonicus should be run under?  I'm trying to build a 1.14.3 map, and have failed with openJDK versions 8, 10, 11.  Each version I've used produces different error messages.  I can provide any if it would be helpful

Thanks

**Comment by skoeven** [comment]
The current release of Tectonicus (2.26.01) is only compatible with Minecraft up to 1.12.2.  I should probably add this to documentation.  In the past I've been able to update Tectonicus to new Minecraft versions relatively quickly, but the extensive changes in 1.13 and personal life stuff (new baby, etc.) have meant I've fallen way behind.
There is a code branch in progress for Minecraft 1.13 support, so if you're comfortable building code you could give it a try, though nothing has been done yet to support 1.14 and unfortunately I'm sure there will be changes needed.

**Comment by skoeven** [comment]
Also I realized that I did not answer your original question.  Tectonicus supports Java 8.  It should run fine on newer Java runtimes as well, but I have not actually tested this.

**Comment by ckbrewer33** [comment]
Thanks skoeven, I understand the 'life' thing all too well :)
