### ISSUE TITLE
"Inconsistency detected by ld.so: ... failed!"

### ISSUE THREAD

**Issue by emma-goldman** [tectonicus/tectonicus#104]
any chance to get help with this issue?

end of the output in console is:
`
Player skin cache is corrupt, cleaning...
Creating player icon assembler
Initialising display...
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
`

```
 + + + + + + + + + + + + + + + + + + + + + + +
                  Tectonicus
   Version: null
   Build null
   Constructed on null at null
   www.github.com/tectonicus/tectonicus  
 + + + + + + + + + + + + + + + + + + + + + + +
Started on Sun Dec 15 21:32:47 CET 2019
System:
	OS Name: Linux
	OS Architecture: amd64
	OS Version: 5.0.0-36-generic
	Java vendor: Ubuntu
	Java version: 11.0.4
	Awt toolkit: sun.awt.X11.XToolkit
	Headless?: null
Settings:
	mode:CommandLine
	rasteriser:Lwjgl
	outputDir:/home/POO/GMZ/mc/tectonicus/Worlds
	useCache:true
	cacheDir:/home/POO/GMZ/mc/tectonicus/cache
	minecraftJar:/home/POO/GMZ/mc/Minecraft_1.14.4_Forge/versions/1.15/1.15.jar
	texturePack:/home/POO/GMZ/mc/tectonicus/Tectonicus-2.26.01
	useOldColorPalette:false
	colourDepth:32
	alphaBits:8
	numSamples:4
	tileSize:512
	numZoomLevels:8
	portalsInitiallyVisible:true
	showSpawn:true
	signsInitiallyVisible:true
	playersInitiallyVisible:true
	bedsInitiallyVisible:true
	spawnInitiallyVisible:true
	viewsInitiallyVisible:true
	eraseOutputDir:false
	extractLwjglNatives:true
	isVerbose:false
	forceLoadAwt:false
	force32BitNatives:false
	force64BitNatives:false
	logFile:/home/POO/GMZ/mc/tectonicus/TectonicusLog.txt
	outputHtmlName:index.html
	numDownsampleThreads:2
	singlePlayerName:Dhr_D_Bosch
'Lanternhead' map
	worldDir: /home/POO/GMZ/mc/Minecraft_1.14.4_Forge/saves/Lanternhead
	dimension: Ender
	cameraAngle: 45
	cameraElevation: 45
	closestZoomSize: 12
	worldSubset: CircularWorldSubset (0, 0) 2000
	useBiomeColours: false
	'Day' layer
		renderStyle: Regular
		lightStyle: Day
		imageFormat: Jpg
		imageCompressionLevel: 0.85
		customBlockConfig: 
	'Night' layer
		renderStyle: Regular
		lightStyle: Night
		imageFormat: Jpg
		imageCompressionLevel: 0.85
		customBlockConfig: 
	'Caves' layer
		renderStyle: Regular
		lightStyle: Day
		imageFormat: Jpg
		imageCompressionLevel: 0.85
		customBlockConfig: 
Player skin cache is corrupt, cleaning...
Creating player icon assembler
Initialising display...

```
System info:
Kubuntu 18.04.3 LTS
i7-4770k, 32gb ram, 2xGTX1080
using nvidia proprietary drivers installed from source.

I have both java 8 & 11 installed, could this be the problem? If so, is there an easy way to make java use a particular runtime from command?
On Archlinux I can use 
`# archlinux-java set`
but not sure under ubuntu.

Also tried it with the simple config but same result.
Cheers

**Comment by alcatraz627** [comment]
I have the same issue on a Ubuntu 19.10 with openjdk-11 and 8

**Comment by skoeven** [comment]
There is a new release of Tectonicus available [https://github.com/tectonicus/tectonicus/releases/tag/v2.27](https://github.com/tectonicus/tectonicus/releases/tag/v2.27)
It is fully compatible with Minecraft 1.13 and 1.14 and partially with 1.15.  (Full support for 1.15 and 1.16 is coming soon.)  This release also moves from LWJGL2 to LWJGL3 which should resolve the issue seen here.  For now I'm going to close this issue.
