### ISSUE TITLE
Java issue on CentOS 8

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#119]
```
[turtle@mcmap Tectonicus]$ /usr/bin/java -Xms2048m -Xmx4096m -jar Tectonicus.jar config=Tectonicus-2.28/simpleConfig.xml 
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Parsing config from /mnt/d7afb2aa-69c5-4151-9729-c6ed37bfd7c7/tectonicus/mc/Tectonicus/Tectonicus-2.28/simpleConfig.xml
No Minecraft jar specified.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/config/Configurator
	at tectonicus.TectonicusApp.<init>(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.config.Configurator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

I'm sure this is pretty basic but I'm struggling to get it figured out.  New VM running CentOS 8.  No matter what config.xml I use I get this came java error.

Currently running
```
$ which java
/usr/bin/java
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

Also, let me add that I'm so happy to see development going on here again!

**Comment by turtle2472** [comment]
Hmmm....  Found the log4j-api and log4jcore in the lib folder and copied those to the same folder as the Tectonicus.jar.  That got me past this issue.  We would get docs updated to show they are needed.  It gave me a new error to troubleshoot, but at least java is trying to do its thing now!

**Comment by skoeven** [comment]
Glad to see someone still interested in using Tectonicus. :)
Apparently log4j is very finicky about being put into an uber jar.  I've had no luck getting it working with the Tectonicus uber jar so I was forced to leave it external.  I do have one other option I'm going to try, but for now you have to copy the Log4j jars around.  I'll see about updating the main readme with some more up to date usage info.

**Comment by Pekkhum** [comment]
Many users are excited to see you back on this project. I didn't want to
interject into the tickets, but this seems the right time to thank you and
those who have helped for their time. 😃
