### ISSUE TITLE
Rendering aborts / no html file

### ISSUE THREAD

**Issue by apnof** [tectonicus/tectonicus#126]
Hello @skoeven and thanks for tectonius.

- When trying to render a map **for an old save**, tectonius seems to freeze with console output 'Finished' and doesn't create a html file. (java process with a couple of Gigabytes still present at this point. seems to exit after a long time). Log shows a NullPointerException.

- Tectonius **runs fine with a test world created with MC 1.16.3** (created new world, stood on spawn for about 1-2 minutes, looking around, saved and quit MC, copied save for rendering)

- May be related to #88 and #93 

End of log shows:
```
[...]
Render Base Tiles
Base render is at zoom 12 with 512x512 tiles
java.lang.NullPointerException
	at tectonicus.rasteriser.MeshUtil.addBlock(Unknown Source)
	at tectonicus.blockTypes.BlockModel.createGeometry(Unknown Source)
	at tectonicus.blockTypes.BlockStateModel.createGeometry(Unknown Source)
	at tectonicus.Chunk.createGeometry(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Writing player skin cache info (2 skins to write)
100%
Player skin cache written
Finished
```

- Config equals `simpleConfig.xml` only with changes to the paths to the source world save and the output path.

- Used commandline: `D:\games\tools\minecraft\Tectonicus-2.28.4\bin>tectonicus.bat -v -c chfConfig.xml`

Java version:
```
D:\games\tools\minecraft\Tectonicus-2.28.4\bin>java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

- The map is pretty old, has "really" been played the last time on 2019-04-30. Before rendering, I loaded it in MC 1.16.3 to update the files to the latest version (just loaded the map, looked around, maybe stepped a distance of 2 blocks or so and saved and quit.)

- Attached you'll find `TectonicusLog.txt`, `TectonicusLog4j.log`, `chfConfig.xml`. (stripped usernames from `TectonicusLog.txt`)
[github-issue_logfiles.zip](https://github.com/tectonicus/tectonicus/files/5397785/github-issue_logfiles.zip)

--> Any ideas?

P.S. unrelated to this problem, just out of interest:
I noticed that my nvidia card is not being used
`19:04:38.629 [main] DEBUG tectonicus.rasteriser.lwjgl.LwjglRasteriser - 	OpenGL Renderer: Intel(R) UHD Graphics 630`
Is there a way to select the more powerful RTX2060 card instead?

edit: just cosmetics

**Comment by skoeven** [comment]
What Minecraft version did you create the failing world with?  Are you using any mods that have custom blocks?  I may need to add some additional logging and have you run Tectonicus again to help narrow down the issue.

As far as choosing the video card goes are you using a laptop?  I'm not sure if there is any easy way to switch GPUs with LWJGL, I'll need to do some research.

**Comment by skoeven** [comment]
I've released a new version that should log out more information if block geometry creation fails: [https://github.com/tectonicus/tectonicus/releases/tag/v2.28.5](https://github.com/tectonicus/tectonicus/releases/tag/v2.28.5)

Also I noticed that the -v command line option was not actually doing anything so I changed it to set the log level to TRACE.  I don't think you'll need to use that flag in this case, as it will print out way more than is needed for this issue.

**Comment by apnof** [comment]
Wow, you are fast :) 
re-rendered in a fresh directory with `tectonicus.bat --verbose --config=chfConfig.xml` with the following output:
```
[...]
Generating portal image...
Outputting block stats to D:\games\tools\minecraft\Tectonicus-2.28.5\out\Map0\blockStats.js
Outputted 0 block counts
Outputting world stats to D:\games\tools\minecraft\Tectonicus-2.28.5\out\Map0\worldStats.js
Outputted world stats
Outputting world vectors to D:\games\tools\minecraft\Tectonicus-2.28.5\out\Map0\worldVectors.js
World vectors done
Texture pack version: VERSION_16
Outputting master contents to D:\games\tools\minecraft\Tectonicus-2.28.5\out\Scripts\contents.js
Exporting html...
Output Html
        writing html to D:\games\tools\minecraft\Tectonicus-2.28.5\out\map.html
Exporting stats...
Outputting stats to D:\games\tools\minecraft\Tectonicus-2.28.5\out\Scripts\stats.js
Writing changed file list...
Output Changed List
Render complete - total time 1 hours 23 minutes 55 seconds
Cleaning up...
Writing player skin cache info (2 skins to write)
100%
Player skin cache written
Finished
```
**No NullPointerException, html has been gerenated**. Crazy. 
Great for debugging if the issue is non-reproducable :-(
Here are the logfiles: [github-issue_logfiles_2.28.5.zip](https://github.com/tectonicus/tectonicus/files/5409294/github-issue_logfiles_2.28.5.zip)

But I changed one thing: I set my Nvidia GPU for the java process. Maybe there is another behavior
 than with the Intel card..?  
![tectonius_java](https://user-images.githubusercontent.com/945269/96599373-23fa7680-12f0-11eb-874e-471d962471ec.PNG)
I will reset this option and try again with the Intel GPU. 

Regarding your question: yes, at the moment, I am testing on a (gaming) Laptop with:
- Intel core i7-9750H (UHD Graphics 630)
- Nvidia GeForce RTX 2060
Both cards are enabled and normally, 3D applications choose the Nvidia card automatically.

**Comment by skoeven** [comment]
It looks like maybe the error happened again but the exception handling caught it and let it continue.  Here are the errors I can see in the log: 
```
14:26:30.653 [main] ERROR tectonicus.blockTypes.BlockModel - Error adding block: block/cracked_stone_bricks in [ChunkCoord (-125, 70) / <-3h, 1y> ] in r.-4.2.mca
14:26:30.653 [main] ERROR tectonicus.blockTypes.BlockModel - Error adding block: block/wall_torch in [ChunkCoord (-125, 70) / <-3h, 1y> ] in r.-4.2.mca
```
I'm not sure why there would be problems rendering those blocks.  Would you be able to post a copy of the region file "r.-4.2.mca"?  I can try debugging to see why those blocks are causing problems.

For GPU switching I know GLFW can export some flags that tell Nvidia Optimus to use the discrete GPU but I'm not sure how to use those from LWJGL or even if I can. I'll look into it more.

Tectonicus defaults to generating png images.  These are the highest quality but will also be larger (possibly much larger) than other formats and take slightly longer to render.  I generally just use jpg format with compression set to 0.75 as the image quality seems fine to me and the file size is much smaller.  As an example rendering a 1100 tile subset of a map takes up about 105 MB for png and about 32 MB for jpg with compression 0.75.

To use jpg you can add the following attrubutes to the layer node: `imageFormat="jpg" imageCompressionLevel="0.75"`.  If you want to keep using png there are png optimizer tools such as pngquant or optipng and others that will compress the pngs for you.  The plan is to add something like that into Tectonicus but it's currently not a high priority.

**Comment by apnof** [comment]
Rendering with Intel GPU completed: `Render complete - total time 1 hours 35 minutes 9 seconds`.
(On Nvidia it was `Render complete - total time 1 hours 23 minutes 55 seconds` - no great difference.)

> It looks like maybe the error happened again but the exception handling caught it and let it continue

Ah, now i get it, you added an exception handling, right? [v2.28.4. vs v2.28.5](https://github.com/tectonicus/tectonicus/compare/v2.28.4...v2.28.5#diff-b01622a7079b46f963fa87840801ffaa89575205a6b06b14a6650233c35ad925L67) I was wondering why the rendering finished.

I missed some of your questions: 

> What Minecraft version did you create the failing world with? Are you using any mods that have custom blocks?

Not sure, maybe 1.13? Is there any way to check inside the files? Launcher reports 'last played with' v1.14.4, but not the version, the world has been created with. 
I believe no mods have ever been used.

> For GPU switching I know GLFW can export some flags that tell Nvidia Optimus to use the discrete GPU but I'm not sure how to use those from LWJGL or even if I can. I'll look into it more.

As explained in the previous post, I am using a laptop. 
But no need to do further research on this, at least for me. I can define the GPU with NVidia settings for now. Later on, the rendering should run on my server.

> Tectonicus defaults to generating png images.  [...] To use jpg you can add [...]

Ah, okay, great to know, I will look into it later; for now (debugging) I will stick to the default options.

> I'm not sure why there would be problems rendering those blocks. Would you be able to post a copy of the region file "r.-4.2.mca"? I can try debugging to see why those blocks are causing issues.

Yes, here you go [r.-4.2.zip](https://github.com/tectonicus/tectonicus/files/5410251/r.-4.2.zip)

**Comment by skoeven** [comment]
I found the issue.  There is a 1.13 block ("minecraft:wall_sign") that still exists in that region which was causing the error.  I added some more error handling (f621b7c) that will log out a warning message with the block name and location when Tectonicus encounters an unknown block and otherwise ignore it.  The other blocks that were having errors before are working fine now.
Here's the new release: [https://github.com/tectonicus/tectonicus/releases/tag/v2.28.6](https://github.com/tectonicus/tectonicus/releases/tag/v2.28.6)

**Comment by apnof** [comment]
Verified with 2.28.6. 
No Exception, html file generated.
Rendered **without** debug flag.

Tectonius printed the warning message as intended:
```
[...]
Render Base Tiles
Base render is at zoom 12 with 512x512 tiles
Unable to find minecraft:wall_sign block in registry. World.Location(coord=[ChunkCoord (-125, 70) / <-3h, 1y> ], x=3, y=41, z=1), Region file: r.-4.2.mca
Rendering tile @ 39,39 (tile 73658 of 73658))))
Base tile render complete
[...]
```
Btw, render time is pretty constant (2min difference): `Render complete - total time 1 hours 25 minutes 49 seconds`

Full log here: [github-issue_logfiles_2.28.6.zip](https://github.com/tectonicus/tectonicus/files/5416356/github-issue_logfiles_2.28.6.zip)

Thank you for your support!
Closing issue now.
