### ISSUE TITLE
Maps with 90 degree camera angle do not render correctly

### ISSUE THREAD

**Issue by ComputerJock** [tectonicus/tectonicus#133]
[There is something buggy with the rendering of this comment... some text is being omitted]

I've probably make a beginner's mistake. I rendered a 1.16.3 world using the sample xml file and it came out OK but isometric of course. I then tried the following xml file and, although it ran for 17 hours, the final result was a blank page. I wanted a top-down map since I find that more useful with the axis up/down, left/right. This is my xml file:

 <?xml version="1.0"?>
 <tectonicus version="2">
	<config mode = "cmd"
	outputDir="JeepersCreepers"
        numZoomLevels = "8"
	numDownsampleThreads = "4"
        spawnInitiallyVisible = "true"
        playersInitiallyVisible = "true"
        bedsInitiallyVisible = "true"
        signsInitiallyVisible = "true"
        portalsInitiallyVisible = "true"
        viewsInitiallyVisible = "true" />

	<map name="JeepersCreepers"
	  worldDir="C:/Users/username/AppData/Roaming/.minecraft/saves/JeepersCreepers Backup">
	  cameraAngle="90"
	  cameraElevation="90"
	  <signs filter="none" />
	  <players filter="all" />
	  <portals filter="all" />
	</map>
	<map name="The Nether"
	  worldDir="C:/Users/username/AppData/Roaming/.minecraft/saves/JeepersCreepers Backup">
	  dimension="nether"
	  cameraAngle="90"
	  cameraElevation="90"
	  <players filter="all" />
	  <portals filter="all" />
	  <layer name="Above Ceiling"
	    lighting="day"
	    renderStyle="normal"
	    backgroundColor="#e5e3df"
	    />
	  <layer name="Below Ceiling"
	    lighting="day"
	    renderStyle="nether"
	    backgroundColor="#e5e3df"
	    />
	</map>
	<map name="The End"
	  worldDir="C:/Users/username/AppData/Roaming/.minecraft/saves/JeepersCreepers Backup">
	  dimension="end"
	  cameraAngle="90"
	  cameraElevation="90"
	  <players filter="all" />
	  <portals filter="all" />
	  <layer name=""
	    lighting="day"
	    backgroundColor="#281932"
	    />
	</map>
 </tectonicus>

Here is the resulting map.html:

 <!doctype html>
 <html>
	<head>
		<title>Tectonicus Map</title> 
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />	
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

		<link rel="stylesheet" type="text/css" href="Scripts/leaflet.css" />
		<link rel="stylesheet" type="text/css" href="Scripts/leafletStyles.css" />
		
		<script type="text/javascript" src="Scripts/vue.min.js"></script>
		<script type="text/javascript" src="Scripts/leaflet.js"></script>
		
		<script type="text/javascript" src="Scripts/math.js"></script>
				<script type="text/javascript" src="Map0/players.js"></script>
		<script type="text/javascript" src="Map0/beds.js"></script>
		<script type="text/javascript" src="Map0/portals.js"></script>
		<script type="text/javascript" src="Map0/signs.js"></script>
		<script type="text/javascript" src="Map0/views.js"></script>
		<script type="text/javascript" src="Map0/chests.js"></script>
		<script type="text/javascript" src="Map0/worldVectors.js"></script>
		<script type="text/javascript" src="Map0/blockStats.js"></script>
		<script type="text/javascript" src="Map0/worldStats.js"></script>
		<script type="text/javascript" src="Map1/players.js"></script>
		<script type="text/javascript" src="Map1/beds.js"></script>
		<script type="text/javascript" src="Map1/portals.js"></script>
		<script type="text/javascript" src="Map1/signs.js"></script>
		<script type="text/javascript" src="Map1/views.js"></script>
		<script type="text/javascript" src="Map1/chests.js"></script>
		<script type="text/javascript" src="Map1/worldVectors.js"></script>
		<script type="text/javascript" src="Map1/blockStats.js"></script>
		<script type="text/javascript" src="Map1/worldStats.js"></script>
		<script type="text/javascript" src="Map2/players.js"></script>
		<script type="text/javascript" src="Map2/beds.js"></script>
		<script type="text/javascript" src="Map2/portals.js"></script>
		<script type="text/javascript" src="Map2/signs.js"></script>
		<script type="text/javascript" src="Map2/views.js"></script>
		<script type="text/javascript" src="Map2/chests.js"></script>
		<script type="text/javascript" src="Map2/worldVectors.js"></script>
		<script type="text/javascript" src="Map2/blockStats.js"></script>
		<script type="text/javascript" src="Map2/worldStats.js"></script>

		<script type="text/javascript" src="Scripts/stats.js"></script>
		<script type="text/javascript" src="Scripts/contents.js"></script>
	</head>

	<body>
		<div id="map_canvas" :style="{ backgroundColor: bgcolor }"></div>
		<script type="text/javascript" src="Scripts/leafletMap.js"></script>
	</body>
 </html>

The contents of the 'JeepersCreepers' directory were:

Cache/
Images/
Map0/
Map1/
Map2/
Scripts/
changed.txt
map.html

Each of Map*/Views/ directory was totally empty.
Map0/ had a few .js files.
Map1/ had LayerA/ and LayerB/, and Map2/ had LayerC/
The tiles in each of the three Layer*/ directories appear to be an isometric view of the Overworld.

Is this a bug or beginners error? If my error, what is my error in the xml file?

PS. Thanks for Tectonicus; I am happy to have found an offline mapper utility that is being actively maintained.

**Comment by skoeven** [comment]
This is a known issue, not an error that you've made.  I will add this to the backlog, but unfortunately I don't know that I will have much time to look into it in the near future.  I may have some time over the holidays, but I'm worried this may be a trickier issue to fix so I likely won't be able to really dig into it until January.

**Comment by skoeven** [comment]
So I could have sworn that I was able to reproduce this issue in the past, but with the current version of Tectonicus I am no longer able to reproduce the problem. Maps with 90 degree cameraAngle and cameraElevation are working fine as far as I can tell. I'll go ahead and close this issue.
