### ISSUE TITLE
weird circular artifect around the map subset

### ISSUE THREAD

**Issue by rawbits2010** [tectonicus/tectonicus#146]
The rendered map shows a circular cutout of the world how it should but some tiles are present around it outside the given area. Those blocks are from the exact location of where they are rendered.

![Tectonicus_circular_artifect_bug](https://user-images.githubusercontent.com/25568847/113485172-a5178580-94ac-11eb-9676-ea86dcd3513a.png)
[10YearsAnn_config.txt](https://github.com/tectonicus/tectonicus/files/6253055/10YearsAnn_config.txt)

**Comment by skoeven** [comment]
This could be caused by leftover tiles in the directory that weren't cleared out before a new render.  Not sure if that's the case here though.
