### ISSUE TITLE
Missing Layer and there is no option to switch maps

### ISSUE THREAD

**Issue by rawbits2010** [tectonicus/tectonicus#147]
I have rendered a small subset of my 1.16.5 world with a terra, a nether, and an empty end map. Each with multiple layers set in config. The output in the command line shows that it certainly did some rendering and indeed I see the rendered map in the output directory.
(created Map0 with Layer A-D, Map1 with Layer E-G, and a totally empty Map2 directory)

What I see on the webpage is only Map0 with LayerA-C. Is renderStyle "exploredcaves" is outdated option in the wiki documentation?

Also, I can't see a way to switch to the Nether maps. And is it ok to have an empty directory for the End if I were never been there before?

Below is the config, the end of the output in the commandline, and the log file. (the log file doesn't contain the exceptions somewhy)
[10YearsAnn_config.txt](https://github.com/tectonicus/tectonicus/files/6253067/10YearsAnn_config.txt)
[Tectonicus_layer_missing_bug.txt](https://github.com/tectonicus/tectonicus/files/6253076/Tectonicus_layer_missing_bug.txt)
[TectonicusLog4j.log](https://github.com/tectonicus/tectonicus/files/6253100/TectonicusLog4j.log)

**Comment by skoeven** [comment]
A bit of a late reply, but yes I don't remember if exploredcaves has ever worked since I've been the maintainer of Tectonicus, probably need to see if anything can be done with it or remove it.

If you've never been to the End then nothing will render.
