### ISSUE TITLE
Can't see any of the map overlays like players, chests, etc.. 

### ISSUE THREAD

**Issue by rawbits2010** [tectonicus/tectonicus#148]
Did I do something wrong? There isn't anything marked on the map, not even the player.
[10YearsAnn_config.txt](https://github.com/tectonicus/tectonicus/files/6253117/10YearsAnn_config.txt)
![Tectonicus_no_overlay_bug](https://user-images.githubusercontent.com/25568847/113486063-2ec95200-94b1-11eb-9ca2-43cd1e6dbecb.png)

**Comment by rawbits2010** [comment]
Ok, I looked into the js code and found that it is pretty much just a 5min stub. So I have spent a day dusting off my js skills, looking into Leaflet, and get the code organized and extended.

Now it displays stuff, but I never tried signs and views for example so there is no pop-up for them.
Chests are, as you can see, has the wrong z-order - probably can be sorted. There is no way to separate underground chests to not spoil dungeons and other loots.
And the positioning of markers are pretty much eyeballed magic numbers - I need help with math. (close enough for my ~2000 by ~2000 test map)

Also, I want to implement 2 rendering modes. One for single map / multiple dimensions - with dim changer control and maybe orientation change by clicking the compass or something. The other would be the current just put every map and layer in a flat layer selector - may be good for multiple worlds.

I have put together a Java dev env for adding all these. Tectonicus builds smoothly. I will probably need to poke around in the Java code more, but it would help if someone could walk me around a little.

![tectonicus_leaflet_display_1](https://user-images.githubusercontent.com/25568847/115167466-ff713280-a0b7-11eb-9b7f-f3fb35b27db7.png)
![tectonicus_leaflet_display_2](https://user-images.githubusercontent.com/25568847/115167476-0a2bc780-a0b8-11eb-9eb7-a230629d03b8.png)

**Comment by skoeven** [comment]
I've resurrected the old javascript and got the map markers working again (though some of the math still needs fixing for 1.18).  If you're still around and interested I'd love to see the code for what you did with your Leaflet maps.

**Comment by skoeven** [comment]
Map markers are working again in [v2.29](https://github.com/tectonicus/tectonicus/releases/tag/v2.29)
