### ISSUE TITLE
Support for 1.18

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#168]
Running maps for the first time in a while and noticing a bunch of out of bounds errors in the logs.  Here are some examples:
```
Error while trying to load chunk at (116, -34) from region /mnt/nfs/backups/mcmaps/world/region/r.3.-2.mca
java.lang.ArrayIndexOutOfBoundsException: Index 664108 out of bounds for length 664108
	at tectonicus.Region.loadChunk(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.preProcess(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Error while trying to load chunk at (82, 27) from region /mnt/nfs/backups/mcmaps/world/region/r.2.0.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (155, -3) from region /mnt/nfs/backups/mcmaps/world/region/r.4.-1.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (160, -15) from region /mnt/nfs/backups/mcmaps/world/region/r.5.-1.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (160, -34) from region /mnt/nfs/backups/mcmaps/world/region/r.5.-2.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (63, 20) from region /mnt/nfs/backups/mcmaps/world/region/r.1.0.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (137, -35) from region /mnt/nfs/backups/mcmaps/world/region/r.4.-2.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (152, 4) from region /mnt/nfs/backups/mcmaps/world/region/r.4.0.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (160, 1) from region /mnt/nfs/backups/mcmaps/world/region/r.5.0.mca
java.lang.ArrayIndexOutOfBoundsException
Error while trying to load chunk at (147, 32) from region /mnt/nfs/backups/mcmaps/world/region/r.4.1.mca
java.lang.ArrayIndexOutOfBoundsException
```

There are lots more.  Most of these are chunks that are not carried over from previous versions but newly generated with the recent update to 1.18 for my server (from 1.17.x).  Thankfully it is still running the maps rather than just dying.

Tectonicus 2.28.7
MC 1.18
CentOS Stream 9 (headless)

**Comment by skoeven** [comment]
I'm going to add my todo list for 1.18 support to this issue.  These are some pretty hefty changes so I don't know when this will be done.

- [ ] Support new height limit of 320 and depth of -64
- [ ] New mountain biomes added, many old biomes renamed or removed
- [ ] Ocean biome temperatures may have changed

Many chunk format changes:
- [ ] `Sections` is now lower case `sections`
- [ ] Section `BlockStates` and `Palette` have moved to a new CompoundTag `block_states` and been renamed `data` and `palette` respectively
- [ ] `Biomes` has been changed to palette format and moved to `sections` with a new CompoundTag 'biomes' with 'data' and 'palette' tags
- [ ] `Level` CompoundTag has been removed and all it's children moved up one level
- [ ] `TileEntities` has been renamed `block_entities`
- [ ] New `yPos` value that shows the lowest section position

**Comment by skoeven** [comment]
It's been a long time coming but the latest versions of Minecraft are now supported in [v2.29](https://github.com/tectonicus/tectonicus/releases/tag/v2.29)
