### ISSUE TITLE
tectonicus.exceptions.MissingAssetException: Couldn't load textures

### ISSUE THREAD

**Issue by beeurd** [tectonicus/tectonicus#183]
Hi, sorry, I've been trying to troubleshoot myself but I must be missing something. 
I've clipped the paths down for clarity, but have checked that they are correct.

I've also tried rendering a different world and using different jar versions but still get a similar error.

Any suggestions?

```
[redacted]>java -jar lib\Tectonicus-2.28.7.jar config=world1Full.xml
Parsing config from [redacted]\world1Full.xml
No Minecraft jar specified.
Searching for most recent Minecraft jar...
Minecraft jar version: 1.18.1
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
 + + + + + + + + + + + + + + + + + + + + + + +
                  Tectonicus
   Version: 2.28.7
   Build 495
   Constructed on October 28 2020 at 0949

   www.github.com/tectonicus/tectonicus
 + + + + + + + + + + + + + + + + + + + + + + +
Started on Mon Jan 17 20:00:35 GMT 2022


Using existing player skin cache
Creating player icon assembler
Initialising display...
        display created ok
Creating camera
TileRenderer init complete
Starting Renderer
Starting tile renderer
Loading world from base dir [redacted]\Minecraft\saves\World1 with dimension OVERWORLD
        Full dimension dir: [redacted]\Minecraft\saves\World1
Loading level.dat
Loading textures
Texture pack version: UNKNOWN_VERSION
tectonicus.exceptions.MissingAssetException: Couldn't load textures from [redacted]\AppData\Roaming\.minecraft\versions\1.18.1\1.18.1.jar
        at tectonicus.texture.TexturePack.<init>(Unknown Source)
        at tectonicus.world.World.<init>(Unknown Source)
        at tectonicus.TileRenderer.output(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
Caused by: tectonicus.exceptions.MissingAssetException: Couldn't find icons.png in [redacted]\AppData\Roaming\.minecraft\versions\1.18.1\1.18.1.jar
        ... 5 more
Cleaning up...
Writing player skin cache info (0 skin to write)
100%
Player skin cache written
Finished
```

**Comment by skoeven** [comment]
Tectonicus isn't currently compatible with Minecraft 1.18 worlds.  I haven't had a great deal of time to work on this project this last year so it's lagging behind the Minecraft versions.  I may have some time in the next few months but unfortunately I can't promise anything.

**Comment by skoeven** [comment]
I should add that it will work with any worlds up to Minecraft 1.16.  MC 1.17 worlds should work as well but there is a silly bug in the version checking code (the same error as in your log) that is preventing them from working.  MC 1.18 worlds don't work even with the version checking bug fixed likely because of the height limit changes.

**Comment by beeurd** [comment]
@skoeven Yeah that makes sense. I've been checking out some other mapping applications in the mean time and they all seem to have had issues due to the way world saves have changed. I'm currently using Overviewer on my 1.18 world but they have an issue where it will only map chunks that have actually been visited in 1.18

**Comment by skoeven** [comment]
Tectonicus now supports up to Minecraft 1.20 in [v2.29](https://github.com/tectonicus/tectonicus/releases/tag/v2.29)
