### ISSUE TITLE
Ability to link specific coordinates

### ISSUE THREAD

**Issue by Phoenix616** [tectonicus/tectonicus#198]
It would be nice to be able to link to specific coordinates (e.g. by clicking on the map) and worlds so that they can be shared.

Or is this already supported but not exposed in the interface? If so then exposing that to the user would be good ;D

**Comment by skoeven** [comment]
There is code already existing to update the map url with world coords based on the map center, but it's the last piece that hasn't been updated from Google Maps to work with Leaflet yet.  It's on the todo list though.

**Comment by skoeven** [comment]
This should be working again in the current release [v2.29](https://github.com/tectonicus/tectonicus/releases/tag/v2.29)
