### ISSUE TITLE
Support for 1.20

### ISSUE THREAD

**Issue by skoeven** [tectonicus/tectonicus#220]
New Biome:
- [x] Cherry Grove

New blocks:
- [x] Bamboo blocks
- [x] Calibrated Sculk Sensor
- [x] Cherry leaves
- [x] Cherry wood blocks
- [x] Cherry sapling
- [x] Chiseled bookshelf
- [x] Decorated Pot
- [x] Hanging Signs (both underneath and side variants)
- [x] Piglin head
- [x] Pink petals
- [x] Pitcher plant
- [x] Sniffer Egg
- [x] Suspicious Gravel
- [x] Suspicious Sand
- [x] Torchflower

Block changes:
- [x] Signs can now have text on both sides

Resource packs changes:
- [x] May need to support 'paletted_permutations' ?

**Comment by matej-darebnik** [comment]
I have already added/fixed cherry leaves and hanging, bamboo and cherry signs in #228. According to my testing, all the other blocks already work except:

- piglin head
- chiseled bookshelf
- decorated pot

![Screenshot 2024-03-13 233614](https://github.com/tectonicus/tectonicus/assets/51075039/fc604589-15f5-4532-9fd7-09b676197cdc)

I will look at those when I have some more time.
