### ISSUE TITLE
Segmentation Fault on "Generating Portal Image"

### ISSUE THREAD

**Issue by skoeven** [tectonicus/tectonicus#34]
_From [alexande...@googlemail.com](https://code.google.com/u/114232659682320765834/) on August 13, 2013 01:06:39_

What steps will reproduce the problem? 1. Simply compile on a headless machine
2. Did occour with vnc and xvfb-run
3. Happens always no matter what settings I choose

---------------------------------------------- What is the expected output? What do you see instead? Please attach a full log file. Parsing config from /xxx/tectonicus/myConfig.xml
- \+ + + + + + + + + + + + + + + + + + + + + +
                Tectonicus
  Version: 2.18
  Build 42:110M\r\n
  Constructed on July 1 2013 at 2106
- \+ + + + + + + + + + + + + + + + + + + + + +
  Started on Tue Aug 13 09:00:39 CEST 2013
  System:
  OS Name: Linux
  OS Architecture: i386
  OS Version: 2.6.32-042stab078.27
  Java vendor: Sun Microsystems Inc.
  Java version: 1.6.0_20
  Awt toolkit: null
  Headless?: null
  Settings:
  mode:CommandLine
  rasteriser:Lwjgl
  outputDir:/xxx/tectonicus/sof-world
  useCache:true
  cacheDir:/xxx/tectonicus/sof-world/cache
  minecraftJar:/xxx/tectonicus/minecraft.jar
  texturePack:none
  colourDepth:24
  alphaBits:0
  numSamples:1
  tileSize:512
  numZoomLevels:8
  portalsInitiallyVisible:true
  showSpawn:true
  signsInitiallyVisible:true
  playersInitiallyVisible:true
  bedsInitiallyVisible:true
  spawnInitiallyVisible:true
  viewsInitiallyVisible:true
  eraseOutputDir:true
  extractLwjglNatives:true
  isVerbose:false
  forceLoadAwt:false
  force32BitNatives:true
  force64BitNatives:false
  logFile:/xxx/tectonicus/sof-world/log.txt
  outputHtmlName:index.html
  numDownsampleThreads:4
  singlePlayerName:

'SoF World' map
    worldDir: /xxx/minecraft-sof/sof-world //builded with the newest minecraft server (1.6.2)
    dimension: Terra
    cameraAngle: 45
    cameraElevation: 45
    closestZoomSize: 12
    worldSubset: CircularWorldSubset (0, 0) 100
    useBiomeColours: false
    'Day' layer
        renderStyle: Regular
        lightStyle: Day
        imageFormat: Jpg
        imageCompressionLevel: 0.75
        customBlockConfig: 
    'Night' layer
        renderStyle: Regular
        lightStyle: Night
        imageFormat: Jpg
        imageCompressionLevel: 0.75
        customBlockConfig: 
    'Caves' layer
        renderStyle: ExploredCaves
        lightStyle: Cave
        imageFormat: Jpg
        imageCompressionLevel: 0.75
        customBlockConfig: 

Forcing 32-bit native libraries
Deleting output dir: /programme-soulan/tectonicus/sof-world
Player skin cache is old or corrupt, cleaning...
Creating player icon assembler
Initialising display...
    Drawable: org.lwjgl.opengl.Display$3@1b5998f
    created pbuffer: org.lwjgl.opengl.Pbuffer@888e6c
    used pixel format:   colour:24 depth:16 alpha:0 stencil:0 samples:0
    display created ok
Using rasteriser: tectonicus.rasteriser.lwjgl.LwjglRasteriser@b9e45a
 -- Lwjgl Rasteriser -- 
    type: Offscreen
    width: 2048
    heigth: 2048
    pBuffer: org.lwjgl.opengl.Pbuffer@888e6c
    OpenGL Vendor: Brian Paul
    OpenGL Renderer: Mesa X11
    OpenGL Version: 2.1 Mesa 7.7.1
Creating camera
TileRenderer init complete
StartingRenderer
Starting tile renderer
Loading world from base dir /programme-soulan/minecraft-sof/sof-world with dimension Terra
    Full dimension dir: /programme-soulan/minecraft-sof/sof-world
Loading level.dat
Loading textures
Creating block registry
Loading players
Loading players from /programme-soulan/minecraft-sof/sof-world/players
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Blinkicore.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Slayer2013.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/FlemmiAkur.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/k9dm.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/JackMaundrell.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Treppengobbo.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/mirokey.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Soulan.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Sahiko.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/RufusPlatus.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Kabelkrieger.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Fandarel.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Rukja.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/LufiXx.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Crissiya.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Shaanea.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Moskradur.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Bana.dat
Loading raw player from /programme-soulan/minecraft-sof/sof-world/players/Monkeyrama.dat
    loaded 19 players
Loading ops from /programme-soulan/minecraft-sof/ops.txt
    found 4 players
Detected Anvil save format
CalculatingChunkHashes
Discovering chunks...
Looking for chunks in /programme-soulan/minecraft-sof/sof-world
    found 100 chunks so far
    found 200 chunks so far
    found 300 chunks so far
    found 400 chunks so far
    found 500 chunks so far
    found 600 chunks so far
    found 700 chunks so far
    found 800 chunks so far
    found 900 chunks so far
    found 1000 chunks so far
    found 1100 chunks so far
    found 1200 chunks so far
    found 1300 chunks so far
    found 1400 chunks so far
    found 1500 chunks so far
    found 1600 chunks so far
    found 1700 chunks so far
    found 1800 chunks so far
    found 1900 chunks so far
    found 2000 chunks so far
    found 2100 chunks so far
    found 2200 chunks so far
    found 2300 chunks so far
    found 2400 chunks so far
    found 2500 chunks so far
    found 2600 chunks so far
    found 2700 chunks so far
    found 2800 chunks so far
    found 2900 chunks so far
    found 3000 chunks so far
    found 3100 chunks so far
    found 3200 chunks so far
    found 3300 chunks so far
    found 3400 chunks so far
    found 3500 chunks so far
    found 3600 chunks so far
    found 3700 chunks so far
Found 3793 chunks in total
Found 0 views
Finding visible tiles...
FindVisibleTiles
2&#37;
5&#37;
100&#37;
found 836 total tiles to output
Finding changed tiles since last render...
FindChangedTiles
Generating compass image...
Generating portal image...
Segmentation fault

---------------------------------------------- What version of the product are you using? What is your operating system and Java version? Java:
java version "1.6.0_20"
OpenJDK Runtime Environment (IcedTea6 1.9.13) (6b20-1.9.13-0ubuntu1~10.04.1)
OpenJDK Server VM (build 19.0-b09, mixed mode)

OS:
2.6.32-042stab078.27
Linux version 2.6.32-042stab078.27 (root@rh6-build-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Mon Jul 1 20:48:07 MSK 2013

---------------------------------------------- Please provide any additional information belo...

_Original issue: http://code.google.com/p/tectonicus/issues/detail?id=34_

**Comment by CaseNewmark** [comment]
Having the same problem with Ubuntu 10.04 server and latest java

**Comment by skoeven** [comment]
Closing. If it's still a problem we can open a new issue in the future.
