### ISSUE TITLE
Memory Suggestions

### ISSUE THREAD

**Issue by plasticmind** [tectonicus/tectonicus#59]
I ran into an OutOfMemoryError and came across [this thread](https://github.com/tectonicus/tectonicus/issues/53), which suggests upping the memory for Java.

I'm on an 3.4Ghz iMac with 8 GB of memory, and I'm trying to render a 750 MB map with the following config: 

```
<config
    outputDir="/Users/plasticmind/Desktop/"
    numZoomLevels="8"
/>

<map
    name="The Realm of Plasticmind"
    worldDir="/Users/plasticmind/Library/Application Support/minecraft/saves/The Realm of Plasticmind (Survival)-4"
    dimension="terra"
    closestZoomSize="12"
    cameraAngle="45"
>
    <layer
        name="Day"
        lighting="day"
        renderStyle="normal"
    />
</map>
```

How much memory should I be specifying?

**Comment by skoeven** [comment]
Unfortunately there are no specific values I can tell you that will work for sure.  See Issue #16 for further discussion of this problem.  I can only suggest a few courses of action: first try running tectonicus without any memory switches, second try running with the -xms and -xmx switches and setting different amounts of memory, third, as suggested in #16, you could try experimenting with the -XX:MaxDirectMemorySize switch.
