### ISSUE TITLE
Throws Exception in Headless Linux Environment

### ISSUE THREAD

**Issue by syberphunk** [tectonicus/tectonicus#60]
>Exception in thread "main" java.lang.ExceptionInInitializerError
>        at tectonicus.rasteriser.lwjgl.LwjglRasteriser.<init>(LwjglRasteriser.java:120)
>        at tectonicus.rasteriser.RasteriserFactory.createRasteriser(RasteriserFactory.java:34)
>        at tectonicus.TileRenderer.<init>(TileRenderer.java:154)
>        at tectonicus.TectonicusApp.run(TectonicusApp.java:923)
>        at tectonicus.TectonicusApp.main(TectonicusApp.java:1178)
>Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: No display mode extension is >available
>       at org.lwjgl.opengl.Display.<clinit>(Display.java:141)
>        ... 5 more
>Caused by: org.lwjgl.LWJGLException: No display mode extension is available
>        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:711)
>        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
>        ... 5 more

Tectonicus started with:

>xvfb-run -a '--server-args=-screen 0 640x480x24' java -Dorg.lwjgl.opengl.Display.allowSoftwareOpenGL=true -Dorg.lwjgl.opengl.Display.noinput=true -jar Tectonicus_v2.20.jar config=myconfig.xml

>uname -a:
Linux li285-77 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 GNU/Linux

OS: Debian Jessie 64bit

Posting my config here gets malformed by github's markup. Let's just say it's default and it doesn't matter what I tweak in it.

The steps here, do not help:
http://minecraft.gamepedia.com/Programs_and_Editors/Tectonicus/VPS#Debian_.28e.g._all_apt_based_distributions.2C_also_Ubuntu_before_10.04.29

**Comment by skoeven** [comment]
You need a patched version of xvfb.  I was able to get the steps you linked to working with a newer patch and have added a Debian 8 section to the wiki with steps to use the newer patch.  
I've also uploaded a package which I compiled on a Debian 8 64bit vm which you can try first.  If it doesn't work on your machine you'll need to follow the updated steps on the wiki and compile xvfb yourself.

xvfb_1.16.4-1_amd64.deb: https://drive.google.com/file/d/0B6dnx1lrXQLda0dwSmJqTTVhQzA/view?usp=sharing

**Comment by syberphunk** [comment]
>Initialising display...
>       Drawable: null
>Could not create pbuffer! (colour:24, alpha:8, depth:16, samples:0)
>org.lwjgl.LWJGLException: Could not find GLX 1.3 config from peer info
>        at org.lwjgl.opengl.LinuxPbufferPeerInfo.nInitHandle(Native Method)
>        at org.lwjgl.opengl.LinuxPbufferPeerInfo.<init>(LinuxPbufferPeerInfo.java:52)
>        at org.lwjgl.opengl.LinuxDisplay.createPbuffer(LinuxDisplay.java:1291)
>        at org.lwjgl.opengl.Pbuffer.createPbuffer(Pbuffer.java:234)
>        at org.lwjgl.opengl.Pbuffer.<init>(Pbuffer.java:219)
>        at org.lwjgl.opengl.Pbuffer.<init>(Pbuffer.java:190)
>        at org.lwjgl.opengl.Pbuffer.<init>(Pbuffer.java:166)
>        at tectonicus.rasteriser.lwjgl.LwjglRasteriser.<init>(LwjglRasteriser.java:153)
>        at tectonicus.rasteriser.RasteriserFactory.createRasteriser(RasteriserFactory.java:34)
>        at tectonicus.TileRenderer.<init>(TileRenderer.java:154)
>        at tectonicus.TectonicusApp.run(TectonicusApp.java:923)
>        at tectonicus.TectonicusApp.main(TectonicusApp.java:1178)
>java.lang.RuntimeException: Could not create drawing surface
>        at tectonicus.TileRenderer.<init>(TileRenderer.java:163)
>        at tectonicus.TectonicusApp.run(TectonicusApp.java:923)
>        at tectonicus.TectonicusApp.main(TectonicusApp.java:1178)
>Finished

hm.

> xvfb-run -a xrandr
>xrandr: Failed to get size of gamma for output screen
>Screen 0: minimum 1 x 1, current 640 x 480, maximum 640 x 480
>screen connected 640x480+0+0 0mm x 0mm
 >  640x480        0.00*

**Comment by skoeven** [comment]
Make sure you run this step from the wiki instructions:
* sudo apt-get install libgl1-mesa-swx11 libxcursor1 libxrandr2 libxxf86vm1 x11-xserver-utils xfonts-base
