### ISSUE TITLE
cameraElevation="30" renders an invisible map

### ISSUE THREAD

**Issue by sentaidigital** [tectonicus/tectonicus#62]
[simpleConfig.xml.zip](https://github.com/tectonicus/tectonicus/files/190718/simpleConfig.xml.zip)

Rendering a map with cameraElevation set to 30 renders an map with all invisible tiles.

**Comment by sentaidigital** [comment]
Rendering with that config file produced a map with people and beds floating over nothingness.  Remove the cameraElevation line and the map is rendered as expected.

**Comment by skoeven** [comment]
This is with v2.21 right?  It's probably related to the changes I made to the depth buffer clipping planes. I'll look into it.

**Comment by sentaidigital** [comment]
Yes, v2.21.

**Comment by sentaidigital** [comment]
![screen shot 2016-03-27 at 1 48 19 am](https://cloud.githubusercontent.com/assets/481531/14064030/18515ef8-f3be-11e5-9a9e-1c639ec0c0d0.png)

Would this also be a side-effect of the depth buffer clipping planes?

**Comment by skoeven** [comment]
Yep.  That's what happens when I commit untested code at the last minute before a release. :-)
I've uploaded a new release that should hopefully fix the problem: [v2.21.01](https://github.com/tectonicus/tectonicus/releases/tag/v2.21.01).  Let me know if it works for you.

**Comment by sentaidigital** [comment]
This is fixed in v2.21.01.
