### ISSUE TITLE
Improve processing time by threading chuck discovery

### ISSUE THREAD

**Issue by sentaidigital** [tectonicus/tectonicus#63]
The chuck discovery seems to be single threaded and takes a long time to complete in even modestly explored worlds.  Judging from my disk activity, it's not I/O bound, so I'm guessing it's the chuck hash computations and block stats tallying (e.g., Cake: 1, stone: 1 bazillion) that is taking so long.

Computing for one chunk can clearly be done independently of the other chunks and so should be easy to thread.

**Comment by skoeven** [comment]
This has been included in [v2.29](https://github.com/tectonicus/tectonicus/releases/tag/v2.29)
