### ISSUE TITLE
javaNullPointerException when rendering signs

### ISSUE THREAD

**Issue by sentaidigital** [tectonicus/tectonicus#65]
This is with v2.21.01 and also v2.21:

```
Writing signs to /Users/franklin/Minecraft/Unseen-map/Map0/signs.js
java.lang.NullPointerException
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at tectonicus.TileRenderer.outputSigns(TileRenderer.java:1782)
	at tectonicus.TileRenderer.outputSigns(TileRenderer.java:1734)
	at tectonicus.TileRenderer.output(TileRenderer.java:250)
	at tectonicus.TectonicusApp.run(TectonicusApp.java:925)
	at tectonicus.TectonicusApp.main(TectonicusApp.java:1173)
Outputting players to /Users/franklin/Minecraft/Unseen-map/Map0/players.js


```
I know I have a few signs that should appear, but the signs.js file ends up with none:

```
var Map0_signData=[

];

```

**Comment by skoeven** [comment]
Are you manually pointing to a Minecraft prerelease jar in your config file?

**Comment by sentaidigital** [comment]
Nope, 1.9.  Full config attached.


[mapconfig-jpg-unseen.xml.zip](https://github.com/tectonicus/tectonicus/files/191241/mapconfig-jpg-unseen.xml.zip)

**Comment by skoeven** [comment]
Turns out that when the Minecraft jar was manually set in the config file, a version check that is needed to determine how to process sign text wasn't being run.
Should be fixed now.  Give [v2.21.02](https://github.com/tectonicus/tectonicus/releases/tag/v2.21.02) a try.

**Comment by sentaidigital** [comment]
Looks like v2.21.02 fixes this.  Thanks!  I have one sign that looks normal in the game world but has two unprintable characters at the end of the two middle lines.  In the JS file, they are UTF8 sequences ef 9c 80 and ef 9c 81.  The weird thing is those UTF8 sequences [don't map](http://www.charbase.com/f700-unicode-invalid-character) [to anything.](http://www.charbase.com/f701-unicode-invalid-character)  

I broke and recreated the sign, it's fine now.  That sign was added to the world when we were playing with pre-release snapshots, so it's was probably a Minecraft bug.

You can close this.  Thanks for fixing it.
