### ISSUE TITLE
sign texture / text / view problem

### ISSUE THREAD

**Issue by swbr** [tectonicus/tectonicus#68]
First of all: Thanks for this wonderful tool. 

I've been using it a lot in the past, and now tried it again. However, I encounter two (major) problems with signs.

1. When clicking a sign in the rendered map, I get four lines of JSON-like text:  
![signs4](https://cloud.githubusercontent.com/assets/8761881/14533176/5a3c6970-0264-11e6-8d85-8bc467b2ca9b.png)  
2. Maybe, this also is the reason why views are not rendered.
3. This is a minor issue, but the text rendered on the sign is wider than the sign itself.
4. I played with the `hasPost` proberty of signs in `defaultBlockConfig.xml`. Setting this to `false` doesn't remove the rendered text, but signs are then orientated in 90° steps instead of 22.5°.

I'm running tectonicus 2.20 on openSuse leap 42.1 and openJDK 1.8.0_77-b03

**Comment by skoeven** [comment]
The way sign text is stored changed in Minecraft 1.9 so you need to use a newer version of Tectonicus that supports it.  Here's the latest version: [Tectonicus 2.RV](https://github.com/tectonicus/tectonicus/releases/tag/v2.RV)

**Comment by swbr** [comment]
Thanks a lot. 
With this version, it works fine!
