### ISSUE TITLE
Circular subset: Center view at center of subset and ignore users etc. outside subset

### ISSUE THREAD

**Issue by swbr** [tectonicus/tectonicus#69]
Hi!

My world is quite large, and rendering the full map is not feasible. One reason is that it uses large biomes and people teleport to far distances to build there. One is even building at the border of the world.

So my config contains several maps, each of the same world with different circular subsets. Rendering etc. works fine, but when opening the map, it's always centered at the spawn position, and it's quite impossible to find a rendered area e.g. at 3,000 / 30,000 by scrolling...

So it would be nice if the map would be centered at the center of the subset.

This seems easy to implement, since `WorldVectors.js` already contains this line:

    origin: new google.maps.Point(1.0, 0.9999949),

and playing around with the numbers does shift the initial position on the map. However, I couldn't figure out how to convert minecraft coordinates to google coordinates using the vectors given in the file.

And one minor thing I saw: 
When clicking the users button, I get all users displayed, even those outside the subset. I could bet I've seen this for portals / signs, too, but currently I don't.

I'm running version 2.RV

Thanks a lot!

**Comment by skoeven** [comment]
Having the map center at the subset center is a good idea.  I'm not sure why it doesn't already work that way.  I'll take a look at it.

I fixed sign, portal, and bed icons appearing outside of subset boundaries in v2.21, but it looks like I forgot player icons.  Also paintings might appear outside subset boundaries, unfortunately that's a more difficult issue.

**Comment by swbr** [comment]
Just as comment for those who don't want to wait for the next release:

As quick and dirty workaround, one can edit the file `worldVectors.js` inside `OutputDirectory/MapX` and change the coordinates of the line

    spawnPosition: new WorldCoord(45, 64, 305)

to the desired  (Minecraft) coordinates. This results in an incorrect spawn position on the map, but at least the map centers at this position.

And... as follow up: Tectonicus [has a problem when rendering areas far far away](https://github.com/tectonicus/tectonicus/issues/71).

**Comment by skoeven** [comment]
Thanks for working on this one.  I'm studying for finals right now so I haven't had any time to work on Tectonicus.

**Comment by skoeven** [comment]
I just committed a fix ( b923402 ) for player icons appearing outside subset boundaries.  That should finally resolve the last part of this issue so I'm going to go ahead and close it.
