### ISSUE TITLE
Background of End-dimension renders shouldn't be white

### ISSUE THREAD

**Issue by sab39** [tectonicus/tectonicus#75]
Since the background in the End in-game is a dark purple static texture, renders of the End look weird with white backgrounds. If the renders could be made to use the real in-game background texture that'd be awesome - if not, the ability to set the colour (and defaulting it to dark purple) would be an awesome improvement.

**Comment by skoeven** [comment]
Being able to set the map background color has actually been on my todo list for a while.  I'll give it a higher priority now that I know somebody is interested in it.

**Comment by Pekkhum** [comment]
Transparency would work for png format, but jpg would need the background in the render.

-------- Original message --------

**Comment by sab39** [comment]
Good point. I pretty much always use png for everything so I sometimes forget about the limitations of other formats ;) I think it's worth supporting transparency when the output *is* png, because it allows some cool effects you can't do any other way, like giving the background position:fixed, or not changing with zoom level.

**Comment by FireflyHM** [comment]
Having an option to set/change background colour on maps would be very nice. Right now, the white background for caves is kind of jarring as well.

**Comment by skoeven** [comment]
It took me a while to get to it, but background color can be changed per layer now.  Any End dimension layers will default to a dark purple background.  Add the new attribute `backgroundColor`  and a hex color value to any layer node to change the background color, e.g. `backgroundColor="#281932"`.

I will look at supporting transparency for pngs.

**Comment by skoeven** [comment]
After some investigation I discovered that the code is already all there to handle png transparency!  It hasn't been working because of a couple of bugs that have been sitting there unnoticed since before the software was open sourced.  I'll get a fix in.

**Comment by sab39** [comment]
Nice, thanks!
