### ISSUE TITLE
Map toggle missing for Portals and Beds

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#77]
When viewing the map my toggle buttons for the portals and beds are missing.  The map run does generate the beds.js and portals.js but the toggle never appears on the maps now.  I typically have initially visible disabled for both of these.  If I enable initially visible then they do appear on the maps.

I'm running v2.23 and 1.10.2 for MC.  Let me know if you need any more information.

Thanks again for all the work you are doing on this project.

Here is the log output though I did trim out three of the map layers I build since they all say the same basic thing and have the same problem.

Pastebin for formatting: http://pastebin.com/23Y5xmVg
` 
- \+ + + + + + + + + + + + + + + + + + + + + +
                Tectonicus
  Version: null
  Build null
  Constructed on null at null
  - \+ + + + + + + + + + + + + + + + + + + + + +
    Started on Sun Jul 17 15:33:38 EDT 2016
    System:
    OS Name: Mac OS X
    OS Architecture: x86_64
    OS Version: 10.9.5
    Java vendor: Oracle Corporation
    Java version: 1.8.0_91
    Awt toolkit: sun.lwawt.macosx.LWCToolkit
    Headless?: null
    Settings:
    mode:CommandLine
    rasteriser:Lwjgl
    outputDir:/Volumes/Vault/MCMaps/an
    useCache:true
    cacheDir:/Volumes/Vault/MCMaps/an/Cache
    minecraftJar:/Users/XXXX/Dropbox/mc/core/minecraft.jar
    texturePack:/Users/XXXX/Dropbox/mc/core/AppleNovaXXXXTextures.zip
    colourDepth:32
    alphaBits:0
    numSamples:4
    tileSize:512
    numZoomLevels:7
    portalsInitiallyVisible:true
    showSpawn:true
    signsInitiallyVisible:false
    playersInitiallyVisible:true
    bedsInitiallyVisible:true
    spawnInitiallyVisible:true
    viewsInitiallyVisible:false
    eraseOutputDir:false
    extractLwjglNatives:true
    isVerbose:false
    forceLoadAwt:false
    force32BitNatives:false
    force64BitNatives:false
    logFile:/Users/XXXX/Dropbox/mc/Logs/Tectonicus.log
    outputHtmlName:index.html
    numDownsampleThreads:8
    singlePlayerName:
    'North East' map
    worldDir: /Volumes/Vault/MCMaps/world
    dimension: Terra
    cameraAngle: 45
    cameraElevation: 35
    closestZoomSize: 23
    worldSubset: FullWorldSubset
    useBiomeColours: false
    'Day' layer
    renderStyle: Regular
    lightStyle: Day
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    'Night' layer
    renderStyle: Regular
    lightStyle: Night
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    'South West' map
    worldDir: /Volumes/Vault/MCMaps/world
    dimension: Terra
    cameraAngle: 225
    cameraElevation: 35
    closestZoomSize: 23
    worldSubset: FullWorldSubset
    useBiomeColours: false
    'Day' layer
    renderStyle: Regular
    lightStyle: Day
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    'Night' layer
    renderStyle: Regular
    lightStyle: Night
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    'Overview' map
    worldDir: /Volumes/Vault/MCMaps/world
    dimension: Terra
    cameraAngle: 90
    cameraElevation: 90
    closestZoomSize: 23
    worldSubset: FullWorldSubset
    useBiomeColours: false
    'Day' layer
    renderStyle: Regular
    lightStyle: Day
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    'Night' layer
    renderStyle: Regular
    lightStyle: Night
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    'The End NE' map
    worldDir: /Volumes/Vault/MCMaps/world
    dimension: Ender
    cameraAngle: 45
    cameraElevation: 35
    closestZoomSize: 23
    worldSubset: FullWorldSubset
    useBiomeColours: false
    'The End Day' layer
    renderStyle: Regular
    lightStyle: Day
    imageFormat: Jpg
    imageCompressionLevel: 0.75
    customBlockConfig: 
    Using existing player skin cache
    Creating player icon assembler
    Initialising display...
    Drawable: null
    created pbuffer: org.lwjgl.opengl.Pbuffer@1b4fb997
    used pixel format:   colour:32 depth:24 alpha:0 stencil:0 samples:4
    display created ok
    Using rasteriser: tectonicus.rasteriser.lwjgl.LwjglRasteriser@7e774085
    -- Lwjgl Rasteriser -- 
    LWJGL version: 2.9.3
    type: Offscreen
    width: 2048
    heigth: 2048
    pBuffer: org.lwjgl.opengl.Pbuffer@1b4fb997
    OpenGL Vendor: Apple Computer, Inc.
    OpenGL Renderer: Apple Software Renderer
    OpenGL Version: 2.1 APPLE-9.6.5
    Creating camera
    TileRenderer init complete
    StartingRenderer
    Starting tile renderer
    Loading world from base dir /Volumes/Vault/MCMaps/world with dimension Terra
    Full dimension dir: /Volumes/Vault/MCMaps/world
    Loading level.dat
    Loading textures
    Creating block registry

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Loading players
Loading players from /Volumes/Vault/MCMaps/world/playerdata
Loading raw player from /Volumes/Vault/MCMaps/world/playerdata/…
…
    loaded 33 players
Detected Anvil save format
CalculatingChunkHashes
Discovering chunks...
Looking for chunks in /Volumes/Vault/MCMaps/world
Loaded playerName
Loaded playerName
Loaded playerName
Loaded playerName

Found 69673 chunks in total
Found 0 views
Finding visible tiles...
FindVisibleTiles
100%
found 28368 total tiles to output
Finding changed tiles since last render...
FindChangedTiles
Generating compass image...
Generating portal image...
Writing signs to /Volumes/Vault/MCMaps/an/Map0/signs.js
Outputting players to /Volumes/Vault/MCMaps/an/Map0/players.js
    outputting …
…
Outputted 32 players
Outputting beds to /Volumes/Vault/MCMaps/an/Map0/beds.js
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName's bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName's bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName's bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName's bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName bed
    outputting playerName's bed
    outputting playerName's bed
    outputting playerName's bed
    outputting playerName's bed
    outputting playerName's bed
Outputted 26 beds
Writing portals...
Wrote 65 portals
Writing views...
Generating block image...
Writing chests to /Volumes/Vault/MCMaps/an/Map0/chests.js
Outputting block stats to /Volumes/Vault/MCMaps/an/Map0/blockStats.js
Outputted 363 block counts
Outputting world stats to /Volumes/Vault/MCMaps/an/Map0/worldStats.js
Outputted world stats
Finding changed views...
Found 0 changed views (out of 0 total views)
Drawing Day views...
Drawing Night views...
View rendering done!

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Tile cache directory found and is valid. Using cache at /Volumes/Vault/MCMaps/an/Cache/tileHashes/Map0/LayerA
100%
FindChangedTiles took: 76.798 seconds
RenderBaseTiles
Base render is at zoom 23 with 512x512 tiles
RenderBaseTiles

Base tile render complete
Downsampling to create zoom level 6
Downsampling level 6
    Scanning for next zoom tiles...
    Downsampling 99 tiles into 36 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 5
Downsampling level 5
    Scanning for next zoom tiles...
    Downsampling 36 tiles into 14 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 4
Downsampling level 4
    Scanning for next zoom tiles...
    Downsampling 14 tiles into 5 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 3
Downsampling level 3
    Scanning for next zoom tiles...
    Downsampling 5 tiles into 3 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 2
Downsampling level 2
    Scanning for next zoom tiles...
    Downsampling 3 tiles into 3 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 1
Downsampling level 1
    Scanning for next zoom tiles...
    Downsampling 3 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 0
Downsampling level 0
    Scanning for next zoom tiles...
    Downsampling 2 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling took 2 seconds

The texture file 'assets/minecraft/textures/blocks/usb_charger_side.png' could not be found.
Error while parsing blockConfig element: [Solid: null]

Tile cache directory found and is valid. Using cache at /Volumes/Vault/MCMaps/an/Cache/tileHashes/Map0/LayerB
100%
FindChangedTiles took: 55.622 seconds
RenderBaseTiles
Base render is at zoom 23 with 512x512 tiles
RenderBaseTiles

Base tile render complete
Downsampling to create zoom level 6
Downsampling level 6
    Scanning for next zoom tiles...
    Downsampling 99 tiles into 36 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 5
Downsampling level 5
    Scanning for next zoom tiles...
    Downsampling 36 tiles into 14 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 4
Downsampling level 4
    Scanning for next zoom tiles...
    Downsampling 14 tiles into 5 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 3
Downsampling level 3
    Scanning for next zoom tiles...
    Downsampling 5 tiles into 3 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 2
Downsampling level 2
    Scanning for next zoom tiles...
    Downsampling 3 tiles into 3 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 1
Downsampling level 1
    Scanning for next zoom tiles...
    Downsampling 3 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling to create zoom level 0
Downsampling level 0
    Scanning for next zoom tiles...
    Downsampling 2 tiles into 2 tiles
100%
Finalizing downsampling...
Downsampling complete
Downsampling took 3 seconds
Outputting world vectors to /Volumes/Vault/MCMaps/an/Map0/worldVectors.js
World vectors done

width: 256
height: 256
Outputting master contents to /Volumes/Vault/MCMaps/an/Scripts/contents.js
Exporting html...
OutputHtml
    writing html to /Volumes/Vault/MCMaps/an/index.html
Exporting stats...
Outputting stats to /Volumes/Vault/MCMaps/an/Scripts/stats.js
Writing changed file list...
OutputChangedList
Render complete - total time 40 minutes 43 seconds
Cleaning up...
Writing player skin cache info (37 skins to write)
100%
Player skin cache written
Finished
`

**Comment by skoeven** [comment]
I've already fixed this in the code, as I noticed the issue right after releasing v2.23.  :-)  I want to fix #76 first and then I will put out another release.

**Comment by turtle2472** [comment]
Awesome! I assumed but didn't see a bug report on it.
