### ISSUE TITLE
Compass rotation/elevation not being updated with map

### ISSUE THREAD

**Issue by fishikles** [tectonicus/tectonicus#85]
It seem that the elevation and rotation of the compass are not hard-coded to be 30 and 45 respectively.
As such if you use non-standard cfg the compass is displayed incorrectly.

As far as I can tell this was introduced in commit 6a135e8.

I suspect the solution is to add a bool flag to indicate if renderItem is rendering the compass, and if so revert to:
camera.lookAt(lookX, lookY, lookZ, size, map.getCameraAngleRad(), map.getCameraElevationRad());

Regards,
fishikles

**Comment by skoeven** [comment]
Thanks for catching this, I'll get it fixed.
