### ISSUE TITLE
Debian headless server

### ISSUE THREAD

**Issue by kamcio96** [tectonicus/tectonicus#87]
Hello, I tired to use Tectonicus on Debian dedi server. 
I read http://minecraft.gamepedia.com/Programs_and_editors/Tectonicus/VPS#Debian_.28e.g._all_apt_based_distributions.2C_also_Ubuntu_before_10.04.29 but it dosen't work
Patch log:
```
root@ns3042293:~/tectonicus# patch -p1 xorg-server-X.X.X/hw/vfb/InitOutput.c xvfb-add-randr-support-v2.patch
patching file xorg-server-X.X.X/hw/vfb/InitOutput.c
Hunk #1 FAILED at 66.
Hunk #2 FAILED at 785.
Hunk #3 FAILED at 860.
3 out of 3 hunks FAILED -- saving rejects to file xorg-server-X.X.X/hw/vfb/InitOutput.c.rej
patch: **** Can't reopen file xorg-server-X.X.X/hw/vfb/InitOutput.c : No such file or directory
root@ns3042293:~/tectonicus#
```
versions:
xorg-server_1.16.4-1
Tectonicus-2.24.jar

What mean `You will now have to add a deb-src repository to you /etc/apt/sources.list` ?
Can you help me with it? :/

**Comment by skoeven** [comment]
It looks like your problem is that you need to replace the X.X.X in the commands with the version numbers in the xorg-server directory name (1.16.4).

**Comment by kamcio96** [comment]
Works on unstable Xorg :wink:
