### ISSUE TITLE
No html file generated

### ISSUE THREAD

**Issue by chrismeunier** [tectonicus/tectonicus#88]
So I tried generating a map with the simpleConfig.xml modified with correct paths 
[simpleConfig.txt](https://github.com/tectonicus/tectonicus/files/966900/simpleConfig.txt)
 and everything seems to work fine except the html file to open the map afterwards is nowhere to be found. I have all .js files and ~7Go of data in the LayerA folder

Here is my log file 
[TectonicusLog.txt](https://github.com/tectonicus/tectonicus/files/966899/TectonicusLog.txt)
 I don't think it will help much... do you have an explanation for this problem?
I ran it using this command: `java -Xms4096M -Xmx4096M -jar Tectonicus-2.24.jar config=simpleConfig.xml `

Tell me if you need any other detail

**Comment by skoeven** [comment]
Is that the full log?  It seems to be missing quite a bit.
