### ISSUE TITLE
Update for 1.12 coming?

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#92]
Just checking in to see if an update for 1.12 is on the way with the updated blocks.

I drag my feet updating the server so bugs get worked out of Minecraft before subjecting the players to it.  That normally worked well with the updates for Tectonicus.  I just updated my server so now I'm just wondering when we might expect this to be updated.  Thanks for any help with this.

**Comment by skoeven** [comment]
I do intend on getting an update out, but my spare time has been scarce recently.  I'll see if I can get something out this weekend.

**Comment by skoeven** [comment]
It took me a while longer than I had hoped, but there is finally a new release out: [https://github.com/tectonicus/tectonicus/releases/tag/v2.25](https://github.com/tectonicus/tectonicus/releases/tag/v2.25)

**Comment by turtle2472** [comment]
Thank you so much.  I personally really appreciate it very much as do the guys on my server.

**Comment by skoeven** [comment]
You're welcome, thanks for being patient.  I'm happy that there are still people using the software.  It makes working on it more rewarding.

**Comment by turtle2472** [comment]
Well I can say the guys on my server all appreciate the work you do for this.  We use the maps all the time.  I love that I've been able to fully automate the process so I don't have to manually do a thing and my maps are updated on the website every 6 hours, same for the users.
