### ISSUE TITLE
Map fails to finish rendering for about 50% of worlds

### ISSUE THREAD

**Issue by Ophitoxaemia** [tectonicus/tectonicus#93]
java.lang.NullPointerException 33 into 3902 

"Base render is at zoom 12 with 512x512 tiles
RenderBaseTiles
java.lang.NullPointerException33 of 3902)
)"

No log file written.

DIsplays "Finished" but hangs and does not return to prompt

Subsequent reruns have a different, but consistent failure spot at 1:

"java.lang.NullPointerException1 of 3870)"

$java -jar Downloads/Tectonicus-2.25.jar config=config.xml

Config file:
<?xml version="1.0"?>
<tectonicus version="2">
	<config mode="cmd" outputDir="outputworld"/>
	<map name="mymapname" worldDir="/home/jcre/.minecraft/saves/worldname/">
		<layer name="Day" lighting="day"/>
	</map>
</tectonicus>

Works for some worlds, not clear what's different. The world it failed on above is believed to be small.

I tried setting the downsample cores to 1, no change. 

Surface Laptop, Ubuntu 17.04

$ uname -a
Linux surface 4.11.0-041100rc1-generic x86_64 x86_64 x86_64 GNU/Linux

Thanks!

**Comment by skoeven** [comment]
If it's happening during RenderBaseTiles it most likely means a problem rendering a block.  There should be a stack trace, e.g. NullPointerException at tectonicus.BlockRenderer and so on.  Do you see anything like that?

**Comment by deasmi** [comment]
I'm seeing the same issue. Stack track is 

Base render is at zoom 12 with 512x512 tiles
RenderBaseTiles
java.lang.NullPointerException1 of 88347)
	at tectonicus.blockTypes.BedNew.addEdgeGeometry(Unknown Source)
	at tectonicus.Chunk.createGeometry(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.world.World.draw(Unknown Source)
	at tectonicus.TileRenderer.renderBaseTiles(Unknown Source)
	at tectonicus.TileRenderer.output(Unknown Source)
	at tectonicus.TectonicusApp.run(Unknown Source)
	at tectonicus.TectonicusApp.main(Unknown Source)
Cleaning up...

**Comment by skoeven** [comment]
Thanks for the info, that should help me quite a bit in tracking down what the problem is.  I'll do some testing to see if I can figure it out.

**Comment by folyfy** [comment]
I'm getting this error whenever the world has beds that were placed before 1.12

**Comment by skoeven** [comment]
There is a new release up that should fix this issue: [https://github.com/tectonicus/tectonicus/releases/tag/v2.25.01](https://github.com/tectonicus/tectonicus/releases/tag/v2.25.01)
