### ISSUE TITLE
Doesn't down sample after crash

### ISSUE THREAD

**Issue by Yemto** [tectonicus/tectonicus#95]
So my computer crashed when it was down sampling the map. Since I used catch I had hope it would just continue after I booted again. but all I get is 

> Base tile render complete
> Downsampling to create zoom level 7
> Downsampling level 7
> 	Scanning for next zoom tiles...
> 	Downsampling 0 tiles into 0 tiles

Samething with the other levels, but level 8 (base level) works fine.

**Comment by skoeven** [comment]
This is the same as issue #79.  Some way is needed for Tectonicus to remember or determine which files still need to be downsampled after it has been interrupted or crashed.
