### ISSUE TITLE
Could not open X display connection

### ISSUE THREAD

**Issue by loewyn** [tectonicus/tectonicus#96]
survie@minecraftsurvie:~/dynmap$ sudo sudo java -jar Tectonicus-2.25.01.jar config=config.xml
Parsing config from /home/survie/dynmap/config.xml

                  Tectonicus
   Version: 2.25.01
   Build 317
   Constructed on November 10 2017 at 1212

   www.github.com/tectonicus/tectonicus

Started on Mon Jun 11 16:23:56 UTC 2018
System:
        OS Name: Linux
        OS Architecture: amd64
        OS Version: 4.15.0-22-generic
        Java vendor: Oracle Corporation
        Java version: 1.8.0_171
        Awt toolkit: sun.awt.X11.XToolkit
        Headless?: null
Settings:
        mode:CommandLine
        rasteriser:Lwjgl
        outputDir:/var/www
        useCache:true
        cacheDir:/var/www/Cache
        minecraftJar:/root/.minecraft/bin/minecraft.jar
        texturePack:none
        useOldColorPalette:false
        colourDepth:16
        alphaBits:0
        numSamples:0
        tileSize:512
        numZoomLevels:8
        portalsInitiallyVisible:true
        showSpawn:true
        signsInitiallyVisible:true
        playersInitiallyVisible:true
        bedsInitiallyVisible:true
        spawnInitiallyVisible:true
        viewsInitiallyVisible:true
        eraseOutputDir:false
        extractLwjglNatives:true
        isVerbose:false
        forceLoadAwt:false
        force32BitNatives:false
        force64BitNatives:false
        logFile:/home/survie/dynmap/./TectonicusLog.txt
        outputHtmlName:map.html
        numDownsampleThreads:2
        singlePlayerName:

'My World Map' map
        worldDir: /home/survie/McMyAdmin/Minecraft/world
        dimension: Terra
        cameraAngle: 45
        cameraElevation: 45
        closestZoomSize: 12
        worldSubset: FullWorldSubset
        useBiomeColours: false
        'Day' layer
                renderStyle: Regular
                lightStyle: Day
                imageFormat: Png
                customBlockConfig:

Player skin cache is corrupt, cleaning...
Creating player icon assembler
Initialising display...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at tectonicus.rasteriser.lwjgl.LwjglRasteriser.<init>(Unknown Source)
        at tectonicus.rasteriser.RasteriserFactory.createRasteriser(Unknown Source)
        at tectonicus.TileRenderer.<init>(Unknown Source)
        at tectonicus.TectonicusApp.run(Unknown Source)
        at tectonicus.TectonicusApp.main(Unknown Source)
Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.Display.<clinit>(Display.java:141)
        ... 5 more
Caused by: org.lwjgl.LWJGLException: Could not open X display connection
        at org.lwjgl.opengl.LinuxDisplay.openDisplay(Native Method)
        at org.lwjgl.opengl.LinuxDisplay.incDisplay(LinuxDisplay.java:305)
        at org.lwjgl.opengl.LinuxDisplay.internAtom(LinuxDisplay.java:629)
        at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:734)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
        ... 5 more

I used base config file :
<tectonicus version="2">

	<config
		outputDir="/var/www"
		numZoomLevels="8"
	/>

	<map
		name="My World Map"
		worldDir="/home/survie/McMyAdmin/Minecraft/world"
		dimension="terra"
		closestZoomSize="12"
	>
		<layer
			name="Day"
			lighting="day"
			renderStyle="normal"
		/>
	</map>

</tectonicus>

Thx for helping :)

**Comment by turtle2472** [comment]
Have you ever been able to render on this machine or is this your first attempt?  Is this a headless machine you are trying to render on?

Basically we need to know more about the machine that's attempting to render your maps.

**Comment by loewyn** [comment]
Thx for your reply,
Sorry for my bad english.

This is a new machine, virtual machine, she's running Ubuntu 18.04 with Open jdk 8.

Nothing other important things. 

The server is running with McMyAdmin...

**Comment by turtle2472** [comment]
You need to make sure there are display adapters installed and set up.  I use CentOS personally and went with a full install just because it put all the display dependancies in place and I didn't have to mess with it at all.  I might have had to install vncserver though, I just don't recall.  For running my maps though I set the display like this:
```
cd $tectonicusfolder
vncserver :1
export DISPLAY=:1
/usr/bin/java -Xms2048m -Xmx4096m -jar Tectonicus.jar config=centos.xml
vncserver -kill :1
export DISPLAY=
```

**Comment by loewyn** [comment]
I can't have display adapter on a virtual server.
So if i want to do a render of the map i have to create a desktop VM for that ? 
So sad :(

**Comment by turtle2472** [comment]
It isn't so sad and it can be done headless.  Here is a guide that was published a while ago by others:
https://minecraft.gamepedia.com/Programs_and_editors/Tectonicus/VPS
