### ISSUE TITLE
Google API changes killed my maps

### ISSUE THREAD

**Issue by turtle2472** [tectonicus/tectonicus#98]
So the API thing is a problem for me now.  All my maps are down, my primary one that is current and the acrid older ones.  

I opened this in hopes that there might be some traction on updating the code for either a new map program or a way to update for Google's API requirements.
Specific errors:

> Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version

**Comment by skoeven** [comment]
To test out a possible temporary fix I signed up and got an API key, however I still can't get it to work.  The old version of the API we were using is no longer available and there must be changes in the new version that are not compatible.
So unfortunately it looks like it's going to be broken until I have time to port it over to leaflet.js.  When that will be I honestly have no idea.  I know Overviewer switched to leaflet a while back so I may take a look at their code to see if I can get a jump start on this.

**Comment by turtle2472** [comment]
Any work you do on it will be greatly appreciated by me and the guys who use my maps.  I totally understand life moving on though.  If I knew how to code I'd be happy to pick up the project and help out...but I don't.

**Comment by skoeven** [comment]
Good news!  I spent some time working on this and after looking at what Overviewer does I got maps displaying again.  
There's still a lot of work to do, but I'll see if I can come up with some instructions for how you can manually set up leaflet to at least see your maps again.

**Comment by turtle2472** [comment]
That is awesome news!  I'm glad you were able to put some time in this and keep it alive!

**Comment by gocke004** [comment]
Hello, I was doing my yearly tectnonicus render of my MC server and I am seeing the same errors as @turtle2472 regarding the google APIs. @skoeven I am excited to hear you had made some breakthroughs by looking at the overviewer code. I was curious if there had been any recent progress on resolving this issue? Thank you!

**Comment by skoeven** [comment]
Unfortunately I haven't had any time recently to work on this.  I am finishing my final semester of school as well as working full time so I haven't been able to spend time on Tectonicus.  I'll let you know as soon I as get anything done on it, but it may not be until January.

**Comment by gocke004** [comment]
@skoeven Sounds great. Good luck finishing your final semester of school! Thank you for your work on this!

**Comment by turtle2472** [comment]
@skoeven I do totally understand as well.  I hope you are able to put time into this again and maintain your personal and professional lives.

**Comment by skoeven** [comment]
I have been able to spend a little time on this recently.  The main issue right now is that I can't get the code that converts between 3D Minecraft world coords and 2D Leaflet map coords to work correctly.  My understanding of the math involved is pretty weak so I've actually started watching the Khan Academy Linear Algebra course in the hopes it can help me understand the underlying math rather than just fumbling around blindly.  Unfortunately that means I have no idea when I will be able to fix the problem.

**Comment by skoeven** [comment]
I've finally added the files you can use to view your map with leaflet, see 7ba90ee6.  Copy the three files from that commit (download the repository) into the root directory of your map and then open the leafletMap.html.  
This defaults to showing Map0, LayerA, with minZoom 0 and maxZoom 5.  If you want to see a different map or layer or use different zoom levels you'll need to edit the leafletMap.js file and change minZoom, maxZoom on line 2:
`var mymap = L.map('map_canvas', {crs: L.CRS.Simple, minZoom: 0, maxZoom: 5}).setView([100, -100], 0);`

and/or change Map0 or LayerA on line 9:
`var url = "Map0/LayerA/Zoom"+coords.z+"/"+xBin+"/"+yBin+"/tile_"+coords.x+"_"+coords.y+"."+"png";`

The maps will not center correctly and don't have any markers, but this should at least let you see them again.

**Comment by turtle2472** [comment]
Sweet.  I'll see about making this change in my main maps in the next few days.  Are you planning to implement something like this into future builds of this so it builds from the start?

**Comment by skoeven** [comment]
Yes, I plan on adding this so that these files get created automatically and so that multiple maps/layers are supported again.  It seems like a good idea to get the maps viewable again even if it takes longer to get map markers working.

**Comment by turtle2472** [comment]
I do agree that getting the old maps working again would be awesome and certainly worth putting the effort into.  I've got archives of old worlds my server has had that won't work anymore without this (or me getting a key and coding it in). I just know you mentioned life being what it was and just checking to be sure you would continue development.  What can I say, I really like this mapping option over any other.

Thank you again for working on this.  My guys appreciate it a lot.

**Comment by skoeven** [comment]
I just updated the leaflet files so that you no longer need to manually edit the javascript.  You still need to manually copy the files into the map directory, but then you should be able to use the new control on the map to switch between any maps and layers.

**Comment by skoeven** [comment]
Closing this one.  See #102 for any updates on getting map markers working again.
